pipeline {
        
    agent {
        docker {
            image 'lachlanevenson/k8s-kubectl:v1.28.2' // Образ с кубов
        }
    }
    stages {
        stage('Clone repo') {
            steps {
                echo 'Building..'
                git 'https://github.com/ColdHand/kuber_project'
            }
        }
        stage('Deploy to Minikube') {
            steps {
                withCredentials([file(credentialsId: 'f84da5a7-c3b9-4c8a-9460-7c9f2ecf2970', variable: 'KUBECONFIG_FILE')]) {
                    script {
                        echo 'Applying Kubernetes manifests...'
                        env.KUBECONFIG = "${KUBECONFIG_FILE}"

                        sh 'kubectl apply -f deployment.yaml'
                        sh 'kubectl apply -f service.yaml'
                        sh 'kubectl apply -f ingress.yaml'

                        echo 'Deployment successful!'
                    }
                }
            }
        }            
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}